api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Infrastructure/Book/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Infrastructure/Stock/ApiPlatform/Resource'
            - '%kernel.project_dir%/src/Application/Book/Command'
            - '%kernel.project_dir%/src/Application/Stock/Command'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    exception_to_status:
        'App\Domain\Shared\Exception\NotFoundException': 404
