doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            stock_quantity: App\Infrastructure\Stock\DBAL\Type\StockQuantityType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: Domain
